export const nnfFields = {
  orders: [
    "order_id",
    "customer_full_name",
    "customer_email",
    "order_date",
    "payment_method",
    "payment_amount",
    "payment_fee",
    "delivery_method",
    "delivery_fee",
    "delivery_address",
    "delivery_date",
    "delivery_status",
    "product_name",
    "category_name",
    "supplier_name",
    "supplier_phones",
    "supplier_emails",
    "warehouse_name",
    "warehouse_address",
    "price",
    "quantity",
  ],
  products_stock: [
    "id",
    "product_name",
    "category_name",
    "supplier_name",
    "supplier_phones",
    "supplier_emails",
    "warehouse_name",
    "warehouse_address",
    "price",
  ],
};

export const nf1Fields = {
  orders: [
    "order_id",
    "customer_first_name",
    "customer_last_name",
    "customer_email",
    "order_date",
    "payment_method",
    "payment_amount",
    "payment_fee",
    "delivery_method",
    "delivery_fee",
    "delivery_region",
    "delivery_city",
    "delivery_street",
    "delivery_house",
    "delivery_apartment",
    "delivery_date",
    "delivery_status",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "price",
    "quantity",
  ],
  supplier_contacts: ["supplier_name", "phone", "email"],
  products_stock: [
    "id",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "price",
  ],
};

export const nf2Fields = {
  orders: [
    "id",
    "order_date",
    "customer_first_name",
    "customer_last_name",
    "customer_email",
    "payment_method",
    "payment_amount",
    "payment_fee",
    "delivery_method",
    "delivery_fee",
    "delivery_region",
    "delivery_city",
    "delivery_street",
    "delivery_house",
    "delivery_apartment",
    "delivery_date",
    "delivery_status",
  ],
  order_items: ["order_id", "product_id", "quantity"],
  supplier_contacts: ["supplier_name", "phone", "email"],
  products_stock: [
    "id",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "price",
  ],
};
// export const nf2Fields = {
//   orders: [
//     "id",
//     "order_date",
//     "customer_first_name",
//     "customer_last_name",
//     "customer_email",
//     "payment_method",
//     "payment_amount",
//     "payment_fee",
//     "delivery_method",
//     "delivery_fee",
//     "delivery_region",
//     "delivery_city",
//     "delivery_street",
//     "delivery_house",
//     "delivery_apartment",
//     "delivery_date",
//     "delivery_status",
//   ],
//   order_items: ["order_id", "product_id", "quantity"],
//   suppliers: ["id", "supplier_name"],
//   supplier_contacts: ["supplier_id", "phone", "email"],
//   warehouses: [
//     "id",
//     "warehouse_name",
//     "warehouse_region",
//     "warehouse_city",
//     "warehouse_street",
//     "warehouse_building",
//     "warehouse_apartment",
//   ],
//   products: ["id", "product_name", "category_name", "price"],
//   product_supplier_warehouse: ["product_id", "supplier_id", "warehouse_id"],
//   order_items: [
//     "order_id",
//     "product_id",
//     "supplier_id",
//     "warehouse_id",
//     "quantity",
//   ],
// };

export const nf3Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  payment_methods: ["id", "method_name", "payment_fee"],
  regions: ["id", "region_name"],
  cities: ["id", "city_name", "region_id"],
  streets: ["id", "street_name", "city_id"],
  addresses: ["id", "building", "apartment", "street_id"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contacts: ["supplier_id", "phone", "email"],
  warehouses: ["id", "warehouse_name", "address_id"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier_warehouse: ["product_id", "supplier_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_id",
    "supplier_id",
    "warehouse_id",
    "quantity",
  ],
};

export const nf4Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  payment_methods: ["id", "method_name", "payment_fee"],
  regions: ["id", "region_name"],
  cities: ["id", "city_name", "region_id"],
  streets: ["id", "street_name", "city_id"],
  addresses: ["id", "building", "apartment", "street_id"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contact_phones: ["supplier_id", "phone"],
  supplier_contact_emails: ["supplier_id", "email"],
  warehouses: ["id", "warehouse_name", "address_id"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier_warehouse: ["product_id", "supplier_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_id",
    "supplier_id",
    "warehouse_id",
    "quantity",
  ],
};

export const nf5Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  payment_methods: ["id", "method_name", "payment_fee"],
  regions: ["id", "region_name"],
  cities: ["id", "city_name", "region_id"],
  streets: ["id", "street_name", "city_id"],
  addresses: ["id", "building", "apartment", "street_id"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contact_phones: ["supplier_id", "phone"],
  supplier_contact_emails: ["supplier_id", "email"],
  warehouses: ["id", "warehouse_name", "address_id"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier: ["id", "product_id", "supplier_id"],
  supplier_warehouse: ["id", "supplier_id", "warehouse_id"],
  product_warehouse: ["id", "product_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_supplier_id",
    "supplier_warehouse_id",
    "quantity",
  ],
};
