export const nf1Fields = {
  orders: [
    "order_id",
    "customer_first_name",
    "customer_last_name",
    "customer_email",
    "order_date",
    "payment_method",
    "payment_amount",
    "payment_fee",
    "delivery_method",
    "delivery_fee",
    "delivery_region",
    "delivery_city",
    "delivery_street",
    "delivery_house",
    "delivery_apartment",
    "delivery_date",
    "delivery_status",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "quantity",
    "price",
  ],
  supplier_contacts: ["id", "supplier_name", "phone", "email"],
  products_stock: [
    "id",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "price",
  ],
};

export const nf2Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method",
    "payment_amount",
    "payment_fee",
    "delivery_method",
    "delivery_fee",
    "delivery_region",
    "delivery_city",
    "delivery_street",
    "delivery_house",
    "delivery_apartment",
    "delivery_date",
    "delivery_status",
  ],
  order_items: ["order_id", "product_id", "quantity"],
  supplier_contacts: ["id", "supplier_name", "phone", "email"],
  products_stock: [
    "id",
    "product_name",
    "category_name",
    "supplier_name",
    "warehouse_region",
    "warehouse_city",
    "warehouse_street",
    "warehouse_building",
    "warehouse_apartment",
    "price",
  ],
};

export const nf3Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_addresses: [
    "id",
    "region_id",
    "city",
    "street",
    "house",
    "apartment",
  ],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  regions: ["id", "region_name"],
  delivery_region_payments: [
    "delivery_method_id",
    "region_id",
    "payment_method_id",
  ],
  payment_methods: ["id", "method_name", "payment_fee"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contacts: ["supplier_id", "phone", "email"],
  warehouses: ["id", "region_id", "city", "street", "building", "apartment"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier_warehouse: ["product_id", "supplier_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_id",
    "supplier_id",
    "warehouse_id",
    "quantity",
  ],
};

export const nf4Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_addresses: [
    "id",
    "region_id",
    "city",
    "street",
    "house",
    "apartment",
  ],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  regions: ["id", "region_name"],
  delivery_payments: ["delivery_method_id", "payment_method_id"],
  region_payments: ["region_id", "payment_method_id"],
  payment_methods: ["id", "method_name", "payment_fee"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contact_phones: ["supplier_id", "phone"],
  supplier_contact_emails: ["supplier_id", "email"],
  warehouses: ["id", "region_id", "city", "street", "building", "apartment"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier_warehouse: ["product_id", "supplier_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_id",
    "supplier_id",
    "warehouse_id",
    "quantity",
  ],
};

export const nf5Fields = {
  customers: ["id", "first_name", "last_name", "email"],
  delivery_addresses: [
    "id",
    "region_id",
    "city",
    "street",
    "house",
    "apartment",
  ],
  delivery_methods: ["id", "method_name", "delivery_fee"],
  regions: ["id", "region_name"],
  delivery_payments: ["delivery_method_id", "payment_method_id"],
  region_payments: ["region_id", "payment_method_id"],
  payment_methods: ["id", "method_name", "payment_fee"],
  orders: [
    "id",
    "order_date",
    "customer_id",
    "payment_method_id",
    "delivery_method_id",
    "delivery_address_id",
    "delivery_date",
    "delivery_status",
  ],
  categories: ["id", "category_name"],
  suppliers: ["id", "supplier_name"],
  supplier_contact_phones: ["supplier_id", "phone"],
  supplier_contact_emails: ["supplier_id", "email"],
  warehouses: ["id", "region_id", "city", "street", "building", "apartment"],
  products: ["id", "product_name", "category_id", "price"],
  product_supplier: ["product_id", "supplier_id"],
  supplier_warehouse: ["supplier_id", "warehouse_id"],
  product_warehouse: ["product_id", "warehouse_id"],
  order_items: [
    "order_id",
    "product_id",
    "supplier_id",
    "warehouse_id",
    "quantity",
  ],
};
