export const SIZE_PRESETS = {
  s1: {
    customers: 10,
    regions: 10,
    delivery_region_payments: 30,
    delivery_addresses: 25,
    orders: 30,
    categories: 10,
    products: 15,
    suppliers: 10,
    warehouses: 10,
    maxWarehousesPerProduct: 4,
    maxProductsPerSupplier: 5,
    product_supplier_warehouse: 50,
    order_items: 80,
  },
  s2: {
    customers: 15,
    regions: 20,
    delivery_region_payments: 50,
    delivery_addresses: 60,
    orders: 80,
    categories: 20,
    products: 25,
    suppliers: 15,
    warehouses: 15,
    maxWarehousesPerProduct: 5,
    maxProductsPerSupplier: 6,
    product_supplier_warehouse: 100,
    order_items: 250,
  },
  s3: {
    customers: 30,
    regions: 27,
    delivery_region_payments: 70,
    delivery_addresses: 120,
    orders: 150,
    categories: 25,
    products: 30,
    suppliers: 20,
    warehouses: 20,
    product_supplier_warehouse: 200,
    maxWarehousesPerProduct: 6,
    maxProductsPerSupplier: 7,
    order_items: 500,
  },
  s4: {
    customers: 50,
    regions: 27,
    delivery_region_payments: 120,
    delivery_addresses: 240,
    orders: 300,
    categories: 30,
    products: 35,
    suppliers: 28,
    warehouses: 25,
    product_supplier_warehouse: 500,
    maxWarehousesPerProduct: 7,
    maxProductsPerSupplier: 9,
    order_items: 1000,
  },
  s5: {
    customers: 100,
    regions: 27,
    delivery_region_payments: 150,
    delivery_addresses: 480,
    orders: 600,
    categories: 33,
    products: 45,
    suppliers: 35,
    warehouses: 35,
    product_supplier_warehouse: 1000,
    maxWarehousesPerProduct: 10,
    maxProductsPerSupplier: 12,
    order_items: 2000,
  },
};
